name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  
  pull_request:
    branches: ["main"]

jobs:

  build-docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker compose
      run: docker compose up
